	<?php $this->getMessage(); ?>

		<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>
			<tr bgcolor=#505050>
				<td colspan=2 style=color:#fff; colspan=2><b>Wyslij wiadomosc do klienta:</b></td>
			</tr>
<?php if($check == true) { ?>
	<form method="post" action="index.php?url=kontakt&page=wiadomosc">
			<tr bgcolor=#F1E0C6>
				<td>Wybierz adresata:</td>
				<td>
					<select name="adresat">
						<?php foreach($result as $x): ?>
							<option value=<?php echo $x['email']; ?>><?php echo $x['imie']; ?> <?php echo $x['nazwisko']; ?> [<?php echo $x['login']; ?>] [<?php echo $x['email']; ?>]</option>	
					<?php endforeach ?>
					</select>
				</td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td>Temat wiadomosci:</td>
				<td><input type=text name="temat" maxlength=11></td>
			</tr>
			 <tr bgcolor=#F1E0C6>
				<td>Tresc wiadomosci:</td>
				<td><textarea name="wiadomosc" rows=6 cols=50></textarea></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td></td>
				<td><button class="button" name="wyslij_wiadomosc">Wyslij wiadomosc</button></td>
			</tr>
	</form>
<?php } ?>
<?php if($check == false) { ?>
		<tr bgcolor=#D4C0A1>
			<td colspan=2>Brak klientow do ktorych moglbys wyslac przypomnienie o zaplate rachunku.</td>
		</tr>
<?php } ?>
			<tr>
				<td><a href=index.php?url=profil>Wróć</a></td>
			</tr>

		</table>
