<?php $this->getMessage(); ?>

<?php if(!($this->isLogged())) { ?>
<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>
	<form method="post">
		<tr bgcolor=#505050>
			<td style=color:#fff; colspan=2>LOGOWANIE</td>
		</tr>
		<tr bgcolor=#D4C0A1>
			<td width=50%>Login:</td>
			<td width=50%><input type="text" name="username"></td>
		</tr>
		<tr bgcolor=#F1E0C6>
			<td width=50%>Hasło:</td>
			<td width=50%><input type="password" name="password"></td>
		</tr>
		<tr bgcolor=#D4C0A1>
			<td></td>
			<td><button class="button" name="login">Zaloguj</button></td>
		</tr>
		<tr bgcolor=#F1E0C6>
			<td colspan=2><a href=?url=rejestracja>REJESTRACJA</a></td>
		</tr>	
	</form>
	<tr>
		<td><a href=index.php>Wróć</a></td>
	</tr>

<?php } ?>
<?php if($this->isLogged()) { ?>
	<?php foreach ($result as $x): ?>
		<tr bgcolor=#505050>
			<td style=color:#fff; colspan=2>Witaj <?php echo $x['imie'] ?> <?php echo $x['nazwisko']?>!</td>
		</tr>
		<tr bgcolor=#F1E0C6>
			<td colspan=2><a href='?url=zamowienia'>Twoje zamowienia</a></td>
		</tr>
		<tr bgcolor=#D4C0A1>
			<td colspan=2><a href='?url=uzytkownik&page=edytuj'>Edytuj</a> lub <a href='?url=uzytkownik&page=usun'>usun</a> konto</td>
		</tr>
		<tr bgcolor=#F1E0C6>
			<td colspan=2><a href='?url=wyloguj'>Wyloguj</a></td>
		</tr>
	<?php endforeach ?>
<?php } ?>
<?php if($this->isAdmin()){ ?>
	asdasdasd
<?php } ?>

</table>