<?php $this->getMessage(); ?>

<form method="post">
	<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>

		<tr bgcolor=#505050>
			<td style=color:#fff; colspan=2><b>Opinie wybranego produktu</b></td>
		 </tr>
	<?php if($check == true) { ?>
		<?php foreach($result as $x):
				?>
			<tr bgcolor=#D4C0A1>
				<td width="100px">Ocena:</td>
				<td><?php echo $x['skala']; ?></td>
			</tr>
			 <tr bgcolor=#F1E0C6>
				<td>Opinia:</td>
				<td><?php echo $x['komentarz']; ?></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td width="100px">Autor:</td>
				<td><?php echo $x['imie']; ?> <?php echo $x['nazwisko']; ?><br><small><?php echo date('Y-m-d, G:i:s', $x['data_opinii']); ?></small></td>
			</tr>
			<tr><td><br></td></tr>
		<?php endforeach ?>
	<?php } ?>	  
	<?php if($check == false) { ?>
		<tr bgcolor=#D4C0A1>
			<td colspan=2>Brak opinii o tym produkcie.</td>
		</tr>
	<?php } ?>

		<tr>
			<td><a href=index.php?url=produkt&page=pokaz&id=<?php echo $_GET['id']; ?>>Wróć</a></td>
		</tr>

	</table>
</form>
