<?php $this->getMessage(); ?>

<form method="post">
	<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>

		<tr bgcolor=#505050>
			<td style=color:#fff; colspan=2><b><?php echo $this->produkty['nazwa_produktu']; ?></b></td>
		 </tr>
		 <tr bgcolor=#F1E0C6>
			<td width="150px">Cena magazynowa: </td>
			<td><?php echo $this->produkty['cena_magazynowa']; ?></td>
		  </tr>
		  <tr bgcolor=#D4C0A1>
			<td>Cena obowiazuje od: </td>
			<td><?php echo date('Y-m-d', $this->produkty['obowiazuje_od']); ?></td>
		  </tr>
		  <tr bgcolor=#F1E0C6>
			<td>Cena obowiazuje do: </td>
			<td>
				<?php if($this->produkty['obowiazuje_do'] == NULL) { ?>
					Cena obecnie obowiązuje
				<?php } ?>
				<?php if($this->produkty['obowiazuje_do'] != NULL) { ?>
					<?php echo $this->produkty['obowiazuje_do']; ?>
				<?php } ?>
			</td>
		  </tr>
		  <tr bgcolor=#D4C0A1>
			<td>Cena sprzedazy: </td>
			<td><?php echo $this->produkty['cena_sprzedazy']; ?></td>
		  </tr>
		  <tr bgcolor=#F1E0C6>
			<td>Opis produktu: </td>
			<td><?php echo $this->produkty['opis_produktu']; ?></td>
		  </tr>
		   <tr bgcolor=#D4C0A1>
			<td>Kategoria: </td>
			<td><?php echo $this->produkty['grupa_produktow']; ?></td>
		  </tr>
		  <tr bgcolor=#F1E0C6>
			<td>Przeznaczenie wiekowe: </td>
			<td><?php echo $this->produkty['grupa_wiekowa']; ?></td>
		  </tr>
		   <tr bgcolor=#D4C0A1>
			<td>Ilosc produktu na magazynie: </td>
			<td><?php echo $this->produkty['ilosc_produktow']; ?></td>
		  </tr>
		  
		    <?php if($this->produkty['ilosc_produktow'] > 0) { ?>
			  <tr bgcolor=#F1E0C6 align=center>
				<td colspan=2><a href="?url=koszyk&page=dodaj&id=<?php echo $this->produkty['ID_produktu']; ?>"><b>DODAJ DO KOSZYKA</b></a></td>					
			  </tr>
			<?php } ?>
			<?php if($this->produkty['ilosc_produktow'] <= 0) { ?>
			  <tr bgcolor=#F1E0C6 align=center>
				<td colspan=2><b>Tego produktu jest zbyt malo w Naszym magazynie. <br>Skontaktuj się z pracownikiem sklepu.</b></td>					
			  </tr>
			<?php } ?>
		  
			<tr bgcolor=#D4C0A1 align=center>
				<td colspan=2><a href="index.php?url=zdjecia&id=<?php echo $this->produkty['ID_produktu']; ?>"><img src="uploads/<?php echo $this->produkty['zdjecie']; ?>"  width="240" height="240"></a></td>
			</tr>

		  
		  <?php if($this->isAdmin()) { ?>
			  <tr bgcolor=#D4C0A1>
					<td colspan=2 style="text-align: center;"><a href="index.php?url=produkt&page=edytuj&id=<?php echo $this->produkty['ID_produktu']; ?>">Edytuj</a> | <a href="index.php?url=produkt&page=usun&id=<?php echo $this->produkty['ID_produktu']; ?>">Usun</a></td>	
			  </tr>
		  <?php } ?>
</form>
<form method="post" action="index.php?url=produkt&page=opinia">
		 <input type=text name="id_produktu" hidden value=<?php echo $this->produkty['ID_produktu']; ?>>
		  <tr bgcolor=#505050>
			<td style=color:#fff; colspan=2><b>Przekaz swoja opinie</b></td>
		 </tr>
		
		  <tr bgcolor=#D4C0A1>
			<td>Ocena:</td>
			<td><input type="radio" name="skala" value="1">1 <input type="radio" name="skala" value="2">2 <input type="radio" name="skala" value="3">3 <input type="radio" name="skala" value="4">4 <input type="radio" name="skala" value="5">5</td>
		</tr>
		 <tr bgcolor=#F1E0C6>
			<td>Opinia:</td>
			<td><textarea name="opinia" rows=6 cols=50></textarea></td>
		</tr>
		<tr bgcolor=#D4C0A1>
			<td></td>
			<td><button class="button" name="dodaj_opinie">Dodaj opinie</button></td>
		</tr>
</form>
		<tr bgcolor=#505050>
			<td colspan=2><a href="index.php?url=opinie&id=<?php echo $this->produkty['ID_produktu']; ?>" style=color:#f1e0c6;><b>Zobacz wszystkie opinie do tego produktu</b></a></td>
		 </tr>
		 
		<tr>
			<td><a href=index.php?url=produkt>Wróć</a></td>
		</tr>

	</table>

