<?php $this->getMessage(); ?>
<form method="post">
	<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>
		<tr bgcolor=#505050>
				<td style=color:#fff; colspan=2><b>Dostepne raporty:</b></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td>
					<ul>
						<li><a href="index.php?url=raport&page=faktury">Wygeneruj faktury i rachunki lacznie z adresami</a></li>
					</ul>
				</td>
			</tr>
		<tr>
			<td><a href=index.php?url=profil>Wróć</a></td>
		</tr>
		</table>
		
</form>
