<?php $this->getMessage(); ?>
	
	<form method="post" action="index.php?url=rejestracja&page=pracownik">
		<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>
			<tr bgcolor=#505050>
				<td style=color:#fff; colspan=2><b>Rejestracja pracownika</b></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td width=50%>Login:</td>
				<td width=50%><input type="text" name="login"></td>
			</tr>
			<tr bgcolor=#F1E0C6>
				<td width=50%>Hasło:</td>
				<td width=50%><input type="password" name="haslo" maxlength=30></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td width=50%>Imie:</td>
				<td width=50%><input type="text" name="imie" maxlength=30></td>
			</tr>
			<tr bgcolor=#F1E0C6>
				<td width=50%>Nazwisko:</td>
				<td width=50%><input type="text" name="nazwisko" maxlength=30></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td width=50%>Telefon:</td>
				<td width=50%><input type="text" name="telefon" maxlength=15></td>
			</tr>
			<tr bgcolor=#F1E0C6>
				<td width=50%>E-mail:</td>
				<td width=50%><input type="text" name="email" maxlength=20></td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td></td>
				<td><button class="button" name="zarejestruj">Zarejestruj</button></td>
			</tr>
			<tr>
				<td><a href=index.php?url=profil>Wróć</a></td>
			</tr>

		</table>
	</form>	