	<?php $this->getMessage(); ?>

	<form method="post">
		<table style="width: 500px;" cellpadding=4 cellspacing=1 align=center>
			<tr bgcolor=#505050>
				<td style=color:#fff; colspan=13><b>Usun klienta:</b></td>
			</tr>
			<tr bgcolor=#F1E0C6>
				<td width=100% colspan=2>Czy na pewno chcesz usunac wybranego uzytkownika?</td>
			</tr>
			<tr bgcolor=#D4C0A1>
				<td width=50% align=right><button class="button" name="usun">Tak</button></td>
				<td width=50% align=left><button><a href=index.php?url=uzytkownik>Wróć</a></button></td>
			</tr>
		</table>
	</form>
